-- Realex Cosset Services — Admin image upload setup
-- Run this once in Supabase SQL Editor before using the image upload button.

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images"
on storage.objects for select
to public
using (bucket_id = 'product-images');

drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images"
on storage.objects for update
to authenticated
using (bucket_id = 'product-images' and public.is_admin())
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images"
on storage.objects for delete
to authenticated
using (bucket_id = 'product-images' and public.is_admin());

-- Keep existing order statuses compatible with the admin dashboard.
alter table public.orders drop constraint if exists orders_status_check;
update public.orders set status = lower(trim(status)) where status is not null;
alter table public.orders add constraint orders_status_check
check (status in ('pending','confirmed','preparing','ready','delivered','completed','cancelled'));


-- =========================
-- BUSINESS LOCATIONS
-- =========================
create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default 'Branch',
  address text not null,
  city text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.branches enable row level security;
drop policy if exists "Public can view active branches" on public.branches;
create policy "Public can view active branches" on public.branches for select to anon, authenticated using (active = true or public.is_admin());
drop policy if exists "Admins manage branches" on public.branches;
create policy "Admins manage branches" on public.branches for all to authenticated using (public.is_admin()) with check (public.is_admin());
insert into public.branches (name,type,address,city,sort_order)
select * from (values
 ('Lagos Head Office','Head Office','3 Amudatu Abeke Street, Bariga, Lagos.','Lagos',1),
 ('Lagos Branch Office','Branch','1 Soji Oshodi Street, Pedro, Bariga, Lagos.','Lagos',2),
 ('Ibadan Branch','Branch','FanoWole Oloya Street, Apete / Oloya, Ibadan.','Ibadan',3)
) v(name,type,address,city,sort_order)
where not exists (select 1 from public.branches);


-- =========================
-- LIVE ADVERTISEMENTS
-- =========================
create table if not exists public.advertisements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  image_url text,
  button_text text default 'Order Now',
  button_link text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.advertisements enable row level security;

drop policy if exists "Public can view active advertisements" on public.advertisements;
create policy "Public can view active advertisements"
on public.advertisements for select
to anon, authenticated
using (active = true or public.is_admin());

drop policy if exists "Admins manage advertisements" on public.advertisements;
create policy "Admins manage advertisements"
on public.advertisements for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop trigger if exists advertisements_updated_at on public.advertisements;
create trigger advertisements_updated_at
before update on public.advertisements
for each row execute function public.set_updated_at();

-- Starter advert. Replace/add the image later from Admin > Advertisements.
insert into public.advertisements (title,body,button_text,button_link,active)
select 'Ready-to-Fry Samosa & Spring Roll','Fresh ready-to-fry samosa and spring roll available now. Perfect for home, parties and events.','Order on WhatsApp','https://wa.me/2348180029999',true
where not exists (select 1 from public.advertisements);
