-- Realex Cosset Services
-- Supabase database schema
-- Run this entire file in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- =========================
-- MENU / PRODUCTS
-- =========================
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null default 0 check (price >= 0),
  category text,
  description text,
  image_url text,
  available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- CUSTOMERS
-- =========================
create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null unique,
  email text,
  address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- ORDERS
-- =========================
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text not null,
  phone text not null,
  address text,
  fulfillment_method text not null default 'Delivery'
    check (fulfillment_method in ('Delivery','Pickup')),
  delivery_location text,
  delivery_fee numeric(12,2) not null default 0 check (delivery_fee >= 0),
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  grand_total numeric(12,2) not null default 0 check (grand_total >= 0),
  note text,
  status text not null default 'pending'
    check (status in ('pending','confirmed','preparing','ready','delivered','completed','cancelled')),
  source text not null default 'web',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- ORDER ITEMS
-- =========================
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(12,2) not null default 0,
  quantity integer not null default 1 check (quantity > 0),
  line_total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

-- =========================
-- CATERING REQUESTS
-- =========================
create table if not exists public.catering_requests (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null,
  phone text not null,
  event_type text not null,
  event_date date,
  guests integer check (guests is null or guests > 0),
  location text,
  request text,
  status text not null default 'new'
    check (status in ('new','contacted','quoted','confirmed','completed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- CUSTOM FOOD INQUIRIES
-- =========================
create table if not exists public.food_inquiries (
  id uuid primary key default gen_random_uuid(),
  food_requested text not null,
  quantity text,
  requested_date date,
  details text,
  customer_name text,
  phone text,
  status text not null default 'new'
    check (status in ('new','contacted','quoted','closed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- ADMIN USERS
-- =========================
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text,
  role text not null default 'admin'
    check (role in ('admin','manager')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- =========================
-- UPDATED_AT TRIGGER
-- =========================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_updated_at on public.products;
create trigger products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists customers_updated_at on public.customers;
create trigger customers_updated_at
before update on public.customers
for each row execute function public.set_updated_at();

drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists catering_updated_at on public.catering_requests;
create trigger catering_updated_at
before update on public.catering_requests
for each row execute function public.set_updated_at();

drop trigger if exists inquiries_updated_at on public.food_inquiries;
create trigger inquiries_updated_at
before update on public.food_inquiries
for each row execute function public.set_updated_at();

-- =========================
-- ADMIN CHECK
-- =========================
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
      and active = true
  );
$$;

-- =========================
-- RLS
-- =========================
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.catering_requests enable row level security;
alter table public.food_inquiries enable row level security;
alter table public.admin_users enable row level security;

-- Products: customers may read available products.
drop policy if exists "Public can view available products" on public.products;
create policy "Public can view available products"
on public.products for select
to anon, authenticated
using (available = true or public.is_admin());

drop policy if exists "Admins manage products" on public.products;
create policy "Admins manage products"
on public.products for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Customers: public checkout may create a customer.
drop policy if exists "Public can create customers" on public.customers;
create policy "Public can create customers"
on public.customers for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins manage customers" on public.customers;
create policy "Admins manage customers"
on public.customers for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Orders: customer app can create orders; admins can read/update them.
drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
on public.orders for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins manage orders" on public.orders;
create policy "Admins manage orders"
on public.orders for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Order items: customer app can create items; admins can read/manage.
drop policy if exists "Public can create order items" on public.order_items;
create policy "Public can create order items"
on public.order_items for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins manage order items" on public.order_items;
create policy "Admins manage order items"
on public.order_items for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Catering: public can submit; admins manage.
drop policy if exists "Public can create catering requests" on public.catering_requests;
create policy "Public can create catering requests"
on public.catering_requests for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins manage catering requests" on public.catering_requests;
create policy "Admins manage catering requests"
on public.catering_requests for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Food inquiries: public can submit; admins manage.
drop policy if exists "Public can create food inquiries" on public.food_inquiries;
create policy "Public can create food inquiries"
on public.food_inquiries for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins manage food inquiries" on public.food_inquiries;
create policy "Admins manage food inquiries"
on public.food_inquiries for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Admin users: only admins can read/manage the table.
drop policy if exists "Admins manage admin users" on public.admin_users;
create policy "Admins manage admin users"
on public.admin_users for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- =========================
-- INDEXES
-- =========================
create index if not exists orders_created_at_idx
on public.orders(created_at desc);

create index if not exists orders_status_idx
on public.orders(status);

create index if not exists orders_phone_idx
on public.orders(phone);

create index if not exists order_items_order_id_idx
on public.order_items(order_id);

create index if not exists catering_created_at_idx
on public.catering_requests(created_at desc);

create index if not exists catering_status_idx
on public.catering_requests(status);

create index if not exists inquiries_created_at_idx
on public.food_inquiries(created_at desc);

create index if not exists inquiries_status_idx
on public.food_inquiries(status);

-- =========================
-- REAL MENU SEED DATA
-- =========================
insert into public.products (name, price, category)
select * from (values
  ('Jollof Rice & Barbecue Chicken', 3200, 'Rice'),
  ('Milk Popcorn', 500, 'Snacks'),
  ('Stir-Fried Spaghetti & Barbecue Chicken', 3200, 'Rice'),
  ('Grilled Fish & Fries', 15000, 'Grills'),
  ('Grilled Chicken & Fries', 6000, 'Grills'),
  ('Grilled Turkey & Fries', 8000, 'Grills'),
  ('Small Chops & Barbecue Grilled Chicken', 2500, 'Small Chops'),
  ('Ewa Agoyin & Plantain', 2000, 'Rice'),
  ('Ewa Agoyin', 1000, 'Rice'),
  ('White Rice + Sauce + Meat/Egg', 1200, 'Rice'),
  ('White Rice + Sauce + Chicken', 2500, 'Rice'),
  ('Samosa & Spring Roll — 12 pieces', 2000, 'Small Chops'),
  ('Small Chops — serves 10 people', 18000, 'Small Chops')
) as v(name,price,category)
where not exists (
  select 1 from public.products p where p.name = v.name
);

-- =========================
-- ADMIN SETUP
-- =========================
-- 1. Create the administrator in Supabase:
--    Authentication -> Users -> Add user
--
-- 2. Copy that user's UUID.
--
-- 3. Run this, replacing YOUR_AUTH_USER_UUID:
--
-- insert into public.admin_users (user_id, name, role)
-- values ('YOUR_AUTH_USER_UUID', 'Realex Administrator', 'admin')
-- on conflict (user_id) do update
-- set active = true, role = 'admin';
--
-- IMPORTANT:
-- Never put a Supabase service-role/secret key in the browser.


-- =========================
-- BUSINESS LOCATIONS / BRANCHES
-- =========================
create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default 'Branch',
  address text not null,
  city text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.branches enable row level security;

drop policy if exists "Public can view active branches" on public.branches;
create policy "Public can view active branches"
on public.branches for select
to anon, authenticated
using (active = true or public.is_admin());

drop policy if exists "Admins manage branches" on public.branches;
create policy "Admins manage branches"
on public.branches for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into public.branches (name,type,address,city,sort_order)
select * from (values
 ('Lagos Head Office','Head Office','3 Amudatu Abeke Street, Bariga, Lagos.','Lagos',1),
 ('Lagos Branch Office','Branch','1 Soji Oshodi Street, Pedro, Bariga, Lagos.','Lagos',2),
 ('Ibadan Branch','Branch','FanoWole Oloya Street, Apete / Oloya, Ibadan.','Ibadan',3)
) v(name,type,address,city,sort_order)
where not exists (select 1 from public.branches);

-- Keep order saving secure: customers can INSERT, but only admins can SELECT/UPDATE.
drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
on public.orders for insert
to anon, authenticated
with check (true);

drop policy if exists "Public can create order items" on public.order_items;
create policy "Public can create order items"
on public.order_items for insert
to anon, authenticated
with check (true);


-- =========================
-- LIVE ADVERTISEMENTS
-- =========================
create table if not exists public.advertisements (
  id bigint generated by default as identity primary key,
  title text not null, body text, image_url text, button_text text default 'Order Now', button_link text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.advertisements enable row level security;
drop policy if exists "Public can view active advertisements" on public.advertisements;
create policy "Public can view active advertisements" on public.advertisements for select to anon, authenticated using (active = true or public.is_admin());
drop policy if exists "Admins manage advertisements" on public.advertisements;
create policy "Admins manage advertisements" on public.advertisements for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop trigger if exists advertisements_updated_at on public.advertisements;
create trigger advertisements_updated_at before update on public.advertisements for each row execute function public.set_updated_at();
insert into public.advertisements (title,body,button_text,button_link,active) select 'Ready-to-Fry Samosa & Spring Roll','Fresh ready-to-fry samosa and spring roll available now. Perfect for home, parties and events.','Order on WhatsApp','https://wa.me/2348180029999',true where not exists (select 1 from public.advertisements);
